language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l fiveam
       -e '(ql:quickload :trivial-openstack-test)
           (setf fiveam:*debug-on-error* t)
           (setf fiveam:*debug-on-failure* t)
           (setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(trivial-openstack-test:run-all-test)'
